version: '3.1'

# SERVICES
services:
  # DATABASE - MARIADB
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - 42-network
  # WORDPRESS
  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        DOMAIN: ${DOMAIN}
    container_name: wordpress
    restart: on-failure
    env_file: .env
    volumes:
      - wp_volume:/var/www/${DOMAIN}
    depends_on:
      - mariadb
    networks:
      - 42-network
  # SERVER - NGINX
  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN: ${DOMAIN}
    container_name: nginx
    restart: on-failure
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/${DOMAIN}
    depends_on:
      - wordpress
    networks:
      - 42-network

# NETWORK
networks:
  42-network:

# VOLUMES
volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${LOGIN}/data/wordpress"
  db_volume:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${LOGIN}/data/mariadb"
      