FROM alpine:3.14

LABEL maintainer="Althaus Yves <yalthaus@student.42lausanne.ch>"

RUN apk update && apk upgrade && \
    apk add --no-cache --quiet --update \
        mariadb mariadb-client vim

RUN mkdir -p /var/lib/mysqld /run/mysqld

COPY ./conf/create_db.sql /tmp/create_db.sql

COPY ./conf/mariadb-server.cnf /etc/my.cnf.d/

COPY ./scripts/entrypoint.sh /tmp/db_entrypoint.sh

RUN chmod +x /tmp/db_entrypoint.sh

CMD [ "sh", "/tmp/db_entrypoint.sh" ]