FROM alpine:3.14

LABEL maintainer="Yves Althaus <yalthaus@st0udent.42lausanne.ch>"

ARG DOMAIN
ARG DIR=/var/www/${DOMAIN}

RUN apk update && apk upgrade \
    && apk add --no-cache --quiet --update \
    php7 php-phar php-json php-curl php-fpm php-mysqli php-iconv vim curl bash mariadb-client

WORKDIR ${DIR}

RUN curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar --output /usr/bin/wp
RUN chmod +x /usr/bin/wp

COPY conf/php.conf.ini /usr/local/etc/php/conf.d/conf.ini
COPY conf/phpinfo.php /conf/phpinfo.php
COPY ./scripts/entrypoint.sh /tmp/entrypoint.sh

RUN chmod +x /tmp/entrypoint.sh

ENTRYPOINT ["sh", "/tmp/entrypoint.sh"]
