FROM alpine:3.14

LABEL maintainer="Yves Althaus <yalthaus@st0udent.42lausanne.ch>"

ARG DOMAIN

RUN apk update && apk upgrade \
    && apk add --no-cache --quiet --update \
    	   nginx openssl vim

RUN	mkdir -p /etc/nginx/ssl/private /etc/nginx/ssl/certs

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/private/$DOMAIN.key \
    -out /etc/nginx/ssl/certs/$DOMAIN.crt \
    -subj "/C=CH/ST=Geneva/L=Geneva/O=42/OU=42/CN=$DOMAIN"

RUN mkdir -p /var/run/nginx

COPY ./conf/nginx.conf /etc/nginx/http.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]