FROM alpine:3.14

LABEL maintainer="Yves Althaus <yalthaus@st0udent.42lausanne.ch>"

ARG DOMAIN

RUN apk update && apk upgrade \
    && apk add --no-cache --quiet --update \
    	   nginx openssl vim

EXPOSE 443

RUN	mkdir -p /etc/nginx/ssl/private /etc/nginx/ssl/certs

RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
        -out /etc/nginx/ssl/certs/$DOMAIN.crt \
        -keyout /etc/nginx/ssl/private/$DOMAIN.key \
        -subj "/C=CH/ST=Switzerland/L=Lausanne/O=42 School/OU=42Lausanne/CN=${DOMAIN}/"


RUN mkdir -p /var/run/nginx

COPY ./conf/nginx.conf /etc/nginx/http.d/default.conf

CMD ["nginx", "-g", "daemon off;"]